/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainme;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import org.python.core.PyObject;
import org.python.util.PythonInterpreter;

/**
 *
 * @author Sajeewa
 */
public class View extends javax.swing.JFrame implements ActionListener {

    public volatile int clickCount;
    public static ArrayList<JLabel> colorLabels;
    private HashMap<String, String> map;

    private boolean programStart = false;
    private boolean connectWalabot = false;
    PythonConnection pythonConnection;
    private int posTolerance = 0;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();

        buttonStop.setEnabled(false);
        buttonPlay.setEnabled(false);

        clickCount = 0;
        colorLabels = new ArrayList<>();

        radioProgram.setSelected(true);
        radioPlay.setSelected(false);

        buttonSaveCoordinates.setEnabled(false);

        addLabels();
        map = new HashMap<>();
        
        pythonConnection = new PythonConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMode = new javax.swing.ButtonGroup();
        jPanelView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelCurrentPos = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelFileName = new javax.swing.JLabel();
        labelTimeCounter = new javax.swing.JLabel();
        buttonOpen = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonPlay = new javax.swing.JButton();
        sliderTime = new javax.swing.JSlider();
        labelDuration = new javax.swing.JLabel();
        labelMode = new javax.swing.JLabel();
        radioProgram = new javax.swing.JRadioButton();
        radioPlay = new javax.swing.JRadioButton();
        buttonProgramStart = new javax.swing.JButton();
        buttonSaveCoordinates = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textPosTolerance = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonConnectWalabot = new javax.swing.JButton();
        buttonSet = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Train Me");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setName("trainMe"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1085, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelView.setBackground(new java.awt.Color(255, 255, 255));
        jPanelView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelView.setAutoscrolls(true);
        jPanelView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelViewMouseClicked(evt);
            }
        });
        jPanelView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("10");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("11");
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("12");
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanelView.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("13");
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("14");
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("15");
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanelView.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        labelCurrentPos.setBackground(new java.awt.Color(255, 255, 255));
        labelCurrentPos.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labelCurrentPos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCurrentPos.setText("C");
        labelCurrentPos.setOpaque(true);
        labelCurrentPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCurrentPosMouseClicked(evt);
            }
        });
        jPanelView.add(labelCurrentPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel31.setIcon(new javax.swing.ImageIcon("D:\\Projects\\Walabot\\TrainMe\\panel2.jpg")); // NOI18N
        jLabel31.setText("jLabel31");
        jPanelView.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanelView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 770, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFileName.setText("<SONG NAME>");
        jPanel2.add(labelFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, -1));

        labelTimeCounter.setText("00:00:00");
        jPanel2.add(labelTimeCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 50, -1));

        buttonOpen.setText("OPEN");
        buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenActionPerformed(evt);
            }
        });
        jPanel2.add(buttonOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, -1));

        buttonStop.setText("STOP");
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });
        jPanel2.add(buttonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 110, -1));

        buttonPlay.setText("PLAY");
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });
        jPanel2.add(buttonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 110, -1));

        sliderTime.setBackground(new java.awt.Color(255, 255, 255));
        sliderTime.setPaintLabels(true);
        sliderTime.setPaintTicks(true);
        sliderTime.setValue(0);
        jPanel2.add(sliderTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 900, -1));

        labelDuration.setText("00:00:00");
        jPanel2.add(labelDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 35, 50, -1));

        labelMode.setText("Mode:");
        jPanel2.add(labelMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 56, -1, 30));

        radioProgram.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupMode.add(radioProgram);
        radioProgram.setSelected(true);
        radioProgram.setText("Program");
        radioProgram.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioProgramStateChanged(evt);
            }
        });
        jPanel2.add(radioProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        radioPlay.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupMode.add(radioPlay);
        radioPlay.setText("Play");
        radioPlay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioPlayStateChanged(evt);
            }
        });
        jPanel2.add(radioPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        buttonProgramStart.setText("START");
        buttonProgramStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProgramStartActionPerformed(evt);
            }
        });
        jPanel2.add(buttonProgramStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 90, -1));

        buttonSaveCoordinates.setText("SAVE");
        buttonSaveCoordinates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveCoordinatesActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSaveCoordinates, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Range(cm)");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Min");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("20");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));

        jTextField2.setBackground(new java.awt.Color(204, 255, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("300");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, -1));

        jLabel18.setText("Max");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel19.setText("Resolution");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jTextField3.setBackground(new java.awt.Color(204, 255, 204));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("5");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 60, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Theta");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("Min");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel22.setText("Max");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel23.setText("Resolution");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jTextField4.setBackground(new java.awt.Color(204, 255, 204));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("5");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 60, -1));

        jTextField5.setBackground(new java.awt.Color(204, 255, 204));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("20");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 60, -1));

        jTextField6.setBackground(new java.awt.Color(204, 255, 204));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("-20");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, -1));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel24.setText("Min");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextField7.setBackground(new java.awt.Color(204, 255, 204));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("-45");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, -1));

        jLabel25.setText("Max");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jTextField8.setBackground(new java.awt.Color(204, 255, 204));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("45");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 60, -1));

        jLabel26.setText("Resolution");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jTextField9.setBackground(new java.awt.Color(204, 255, 204));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("2");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 60, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Phi");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel28.setText("Threshold");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        jTextField10.setBackground(new java.awt.Color(204, 255, 204));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("40");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 30, -1));

        jLabel32.setText("Tolerance (cm)");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 20));

        jLabel29.setText("Moving Target");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 20));

        textPosTolerance.setBackground(new java.awt.Color(204, 255, 204));
        textPosTolerance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPosTolerance.setText("50");
        textPosTolerance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPosToleranceActionPerformed(evt);
            }
        });
        jPanel1.add(textPosTolerance, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 30, -1));

        jCheckBox1.setBackground(new java.awt.Color(204, 255, 204));
        jCheckBox1.setSelected(true);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        buttonConnectWalabot.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        buttonConnectWalabot.setText("Connect Walabot");
        buttonConnectWalabot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConnectWalabotActionPerformed(evt);
            }
        });
        jPanel1.add(buttonConnectWalabot, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 50));

        buttonSet.setText("SET");
        buttonSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon("D:\\Projects\\Walabot\\TrainMe\\panel1.jpg")); // NOI18N
        jLabel30.setText("Tolerance (cm)");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 260, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLabels() {

        colorLabels.add(jLabel1);
        colorLabels.add(jLabel2);
        colorLabels.add(jLabel3);
        colorLabels.add(jLabel4);
        colorLabels.add(jLabel5);
        colorLabels.add(jLabel6);
        colorLabels.add(jLabel7);
        colorLabels.add(jLabel8);
        colorLabels.add(jLabel9);
        colorLabels.add(jLabel10);
        colorLabels.add(jLabel11);
        colorLabels.add(jLabel12);
        colorLabels.add(jLabel13);
        colorLabels.add(jLabel14);
        colorLabels.add(jLabel15);

    }

    int xCoord, yCoord;
    private void jPanelViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelViewMouseClicked

        xCoord = evt.getX();
        yCoord = evt.getY();
//
//        String s = x + "," + y;
//        coordinates.add(s);

        System.out.println(xCoord + ":" + yCoord);

        if (clickCount < 15) {
            if (!colorLabels.isEmpty()) {
                jPanelView.setLayout(null);
                colorLabels.get(clickCount).setVisible(true);
                colorLabels.get(clickCount).setBackground(Color.GREEN);
                colorLabels.get(clickCount).setLocation(xCoord - 5, yCoord - 5);
            }
        }

        System.out.println("label on panel click:" + colorLabels.get(clickCount).getX() + "," + colorLabels.get(clickCount).getY());

//        
    }//GEN-LAST:event_jPanelViewMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (clickCount == 0) {
            jLabel1.setLocation(0, 0);
            jLabel1.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (clickCount == 1) {
            jLabel2.setLocation(0, 0);
            jLabel2.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (clickCount == 2) {
            jLabel3.setLocation(0, 0);
            jLabel3.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (clickCount == 3) {
            jLabel4.setLocation(0, 0);
            jLabel4.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (clickCount == 4) {
            jLabel5.setLocation(0, 0);
            jLabel5.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (clickCount == 5) {
            jLabel6.setLocation(0, 0);
            jLabel6.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if (clickCount == 6) {
            jLabel7.setLocation(0, 0);
            jLabel7.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if (clickCount == 7) {
            jLabel8.setLocation(0, 0);
            jLabel8.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if (clickCount == 8) {
            jLabel9.setLocation(0, 0);
            jLabel9.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if (clickCount == 9) {
            jLabel10.setLocation(0, 0);
            jLabel10.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void buttonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenActionPerformed

        actionPerformed(evt);
    }//GEN-LAST:event_buttonOpenActionPerformed

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed

        actionPerformed(evt);// TODO add your handling code here:
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed

        actionPerformed(evt);// TODO add your handling code here:
    }//GEN-LAST:event_buttonStopActionPerformed

    private void buttonProgramStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProgramStartActionPerformed

        actionPerformed(evt);// TODO add your handling code here:
    }//GEN-LAST:event_buttonProgramStartActionPerformed

    private void buttonSaveCoordinatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveCoordinatesActionPerformed

        clickCount++;
        String coordinate = xCoord + "," + yCoord + "," + clickCount;
        map.put(labelTimeCounter.getText(), coordinate);
        buttonSaveCoordinates.setEnabled(false);
    }//GEN-LAST:event_buttonSaveCoordinatesActionPerformed

    private void radioPlayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioPlayStateChanged

        if (radioPlay.isSelected()) {
            buttonProgramStart.setEnabled(false);
            buttonSaveCoordinates.setEnabled(false);
        } else {
            buttonProgramStart.setEnabled(true);
        }
    }//GEN-LAST:event_radioPlayStateChanged

    private void radioProgramStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioProgramStateChanged

    }//GEN-LAST:event_radioProgramStateChanged

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if (clickCount == 11) {
            jLabel12.setLocation(0, 0);
            jLabel12.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if (clickCount == 12) {
            jLabel13.setLocation(0, 0);
            jLabel13.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if (clickCount == 13) {
            jLabel14.setLocation(0, 0);
            jLabel4.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if (clickCount == 14) {
            jLabel15.setLocation(0, 0);
            jLabel15.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if (clickCount == 10) {
            jLabel11.setLocation(0, 0);
            jLabel11.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void labelCurrentPosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCurrentPosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCurrentPosMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void buttonConnectWalabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConnectWalabotActionPerformed

        actionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConnectWalabotActionPerformed

    private void textPosToleranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPosToleranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPosToleranceActionPerformed

    private void buttonSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetActionPerformed
        try(  PrintWriter out = new PrintWriter( "Data.txt" )  ){
        String rmin = jTextField1.getText();
        String rmax = jTextField2.getText();
        String rres = jTextField3.getText();
        String tmin = jTextField6.getText();
        String tmax = jTextField5.getText();
        String tres = jTextField4.getText();
        String pmin = jTextField7.getText();
        String pmax = jTextField8.getText();
        String pres = jTextField9.getText();
        String thrs = jTextField10.getText();
        String mti = "";
        if(jCheckBox1.isSelected()) {mti = "True";}
        else {mti = "False";}
        
        out.println(rmin);
        out.println(rmax);
        out.println(rres);
        out.println(tmin);
        out.println(tmax);
        out.println(tres);
        out.println(pmin);
        out.println(pmax);
        out.println(pres);
        out.println(thrs);
        out.println(mti);
        
        
}       catch (FileNotFoundException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSetActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * starting the algo for the audio player
     */
    private AudioPlayer player = new AudioPlayer();
    private Thread playbackThread;
    private PlayingTimer timer;

    private boolean isPlaying = false;
    private boolean isPause = false;

    private String audioFilePath;
    private String lastOpenPath;

    /**
     * Handle click events on the buttons.
     */
    @Override
    public void actionPerformed(ActionEvent event) {
        Object source = event.getSource();
        if (source instanceof JButton) {
            JButton button = (JButton) source;
            if (button == buttonOpen) {
                openFile();
                buttonStop.setEnabled(true);
                buttonPlay.setEnabled(true);
            } else if (button == buttonStop) {
                stopPlaying();
                resetColor();
            } else if (button == buttonPlay) {
                if (!isPlaying) {
                    playBack();
                } else {
                    if (!isPause) {
                        pausePlaying();
                        buttonSaveCoordinates.setEnabled(true);
                    } else {
                        resumePlaying();
                    }
                }

            } else if (button == buttonProgramStart) {
                if (!programStart) {
                    programStart = true;
                    button.setText("END");
                    buttonSaveCoordinates.setEnabled(true);
                } else {
                    programStart = false;
                    button.setText("START");
                    save();
                    map.clear();
                  
                }
            } else if (button == buttonConnectWalabot) {
                if (!connectWalabot) {
                    connectWalabot = true;
                    button.setText("Disconnect Walabot");
                    try{
                           ProcessBuilder pb = new ProcessBuilder("python","SensorApp.py");
                           
                            pb.redirectOutput();
                            pb.redirectError();
                            
//                            BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
                            
                            new Thread(new Runnable() {
                               @Override
                               public void run() {
                                   try {
                                       Process p = pb.start();
                                   } catch (IOException ex) {
                                       Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                                   }
                               }
                           }).start();
                            //while(true){
                                
                                   //System.out.println(in.readLine());
                            //}   
                            
                    }catch(Exception e){
                        e.printStackTrace();
                    }
//                    pythonConnection.connectWalabot();
                    //pythonConnection.callPython();
                } else {
                    connectWalabot = false;
                    button.setText("Connect Walabot");
                    pythonConnection.disconnectWalabot();
                }
            }
        }
    }

    private void openFile() {
        JFileChooser fileChooser = null;
        //resetLabels();

        if (lastOpenPath != null && !lastOpenPath.equals("")) {
            fileChooser = new JFileChooser(lastOpenPath);
        } else {
            fileChooser = new JFileChooser();
        }

        FileFilter wavFilter = new FileFilter() {
            @Override
            public String getDescription() {
                return "Sound file (*.WAV)";
            }

            @Override
            public boolean accept(File file) {
                if (file.isDirectory()) {
                    return true;
                } else {
                    return file.getName().toLowerCase().endsWith(".wav");
                }
            }
        };

        fileChooser.setFileFilter(wavFilter);
        fileChooser.setDialogTitle("Open Audio File");
        fileChooser.setAcceptAllFileFilterUsed(false);

        int userChoice = fileChooser.showOpenDialog(this);
        if (userChoice == JFileChooser.APPROVE_OPTION) {
            audioFilePath = fileChooser.getSelectedFile().getAbsolutePath();
            lastOpenPath = fileChooser.getSelectedFile().getParent();
            if (isPlaying || isPause) {
                stopPlaying();
                while (player.getAudioClip().isRunning()) {
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
            }

            if (radioPlay.isSelected()) {
                read();
            }

        }
    }

    /**
     * Start playing back the sound.
     */
    private void playBack() {

        timer = new PlayingTimer(labelTimeCounter, sliderTime, radioPlay.isSelected(), colorLabels, labelCurrentPos, jPanelView, posTolerance);

        if (radioPlay.isSelected()) {
            timer.setMap(read());
        }
        timer.start();
        isPlaying = true;
        playbackThread = new Thread(new Runnable() {

            @Override
            public void run() {
                try {

                    buttonStop.setText("STOP");
                    buttonStop.setEnabled(true);

                    buttonPlay.setText("PAUSE");
                    buttonPlay.setEnabled(true);

                    player.load(audioFilePath);
                    timer.setAudioClip(player.getAudioClip());
                    labelFileName.setText(audioFilePath);
                    sliderTime.setMaximum((int) player.getClipSecondLength());

                    labelDuration.setText(player.getClipLengthString());
                    player.play();

                    resetControls();

                } catch (UnsupportedAudioFileException ex) {
                    JOptionPane.showMessageDialog(rootPane,
                            "The audio format is unsupported!", "Error", JOptionPane.ERROR_MESSAGE);
                    resetControls();
                    ex.printStackTrace();
                } catch (LineUnavailableException ex) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Could not play the audio file because line is unavailable!", "Error", JOptionPane.ERROR_MESSAGE);
                    resetControls();
                    ex.printStackTrace();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane,
                            "I/O error while playing the audio file!", "Error", JOptionPane.ERROR_MESSAGE);
                    resetControls();
                    ex.printStackTrace();
                }

            }
        });

        playbackThread.start();
    }

    private void stopPlaying() {
        isPause = false;
        buttonPlay.setText("PLAY");
        buttonPlay.setEnabled(true);
        buttonStop.setEnabled(false);
        timer.reset();
        timer.interrupt();
        player.stop();
        playbackThread.interrupt();
    }

    private void pausePlaying() {
        buttonPlay.setText("RESUME");
        isPause = true;
        player.pause();
        timer.pauseTimer();
        playbackThread.interrupt();
    }

    private void resumePlaying() {
        buttonPlay.setText("PAUSE");
        isPause = false;
        System.out.println("label 1 before call resume:" + colorLabels.get(clickCount).getX() + "," + colorLabels.get(clickCount).getY());
        player.resume();
        timer.resumeTimer();
        playbackThread.interrupt();
        System.out.println("label 1 after call resume:" + colorLabels.get(clickCount).getX() + "," + colorLabels.get(clickCount).getY());
    }

    private void resetControls() {
        timer.reset();
        timer.interrupt();

        buttonStop.setText("STOP");

        buttonPlay.setEnabled(true);
        buttonStop.setEnabled(false);

        isPlaying = false;
    }

    /**
     * ending the algo for the audio player
     */
    //
    //
    //serializing the hashmap of coordinates
    private void save() {
        FileOutputStream fos = null;
        try {
            //save coordinates of a particular file
            String fileName = audioFilePath.substring(audioFilePath.lastIndexOf("\\") + 1);
            fileName = fileName.substring(0, fileName.length() - 4);
            File file = new File(fileName + ".ser");
            System.out.println(fileName + ".ser");
            fos = new FileOutputStream(file);
            ObjectOutputStream oos = new ObjectOutputStream(fos);

            oos.writeObject(map);
            oos.flush();
            oos.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    //de-serializing the hashmap of coordinates
    public HashMap<String, String> read() {
        FileInputStream fis = null;
        HashMap<String, String> mapInFile = null;
        try {
            String fileName = audioFilePath.substring(audioFilePath.lastIndexOf("\\") + 1);
            fileName = fileName.substring(0, fileName.length() - 4);
            File file = new File(fileName + ".ser");
            fis = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fis);

            mapInFile = (HashMap<String, String>) ois.readObject();

            ois.close();

        } catch (Exception ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return mapInFile;
    }

    //walabot coordinates
    public void setUserPosition(int userXCoord, int userYCoord) {
        if (radioPlay.isSelected()) {
            labelCurrentPos.setLocation(userXCoord, userYCoord);
        }
    }

    //---------------------------------------------//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnectWalabot;
    private javax.swing.ButtonGroup buttonGroupMode;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonProgramStart;
    private javax.swing.JButton buttonSaveCoordinates;
    private javax.swing.JButton buttonSet;
    private javax.swing.JButton buttonStop;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel labelCurrentPos;
    private javax.swing.JLabel labelDuration;
    private javax.swing.JLabel labelFileName;
    private javax.swing.JLabel labelMode;
    private javax.swing.JLabel labelTimeCounter;
    private javax.swing.JRadioButton radioPlay;
    private javax.swing.JRadioButton radioProgram;
    private javax.swing.JSlider sliderTime;
    private javax.swing.JTextField textPosTolerance;
    // End of variables declaration//GEN-END:variables

    private void resetLabels() {
        jLabel1.setLocation(0, 0);
        jLabel2.setLocation(0, 0);
        jLabel3.setLocation(0, 0);
        jLabel4.setLocation(0, 0);
        jLabel5.setLocation(0, 0);
        jLabel6.setLocation(0, 0);
        jLabel7.setLocation(0, 0);
        jLabel8.setLocation(0, 0);
        jLabel9.setLocation(0, 0);
        jLabel10.setLocation(0, 0);
        jLabel11.setLocation(0, 0);
        jLabel12.setLocation(0, 0);
        jLabel13.setLocation(0, 0);
        jLabel14.setLocation(0, 0);
        jLabel15.setLocation(0, 0);
    }
      private void resetColor(){
        jLabel1.setBackground(Color.LIGHT_GRAY);
        jLabel2.setBackground(Color.LIGHT_GRAY);
        jLabel3.setBackground(Color.LIGHT_GRAY);
        jLabel4.setBackground(Color.LIGHT_GRAY);
        jLabel5.setBackground(Color.LIGHT_GRAY);
        jLabel6.setBackground(Color.LIGHT_GRAY);
        jLabel7.setBackground(Color.LIGHT_GRAY);
        jLabel8.setBackground(Color.LIGHT_GRAY);
        jLabel9.setBackground(Color.LIGHT_GRAY);
        jLabel10.setBackground(Color.LIGHT_GRAY);
        jLabel11.setBackground(Color.LIGHT_GRAY);
        jLabel12.setBackground(Color.LIGHT_GRAY);
        jLabel13.setBackground(Color.LIGHT_GRAY);
        jLabel14.setBackground(Color.LIGHT_GRAY);
        jLabel15.setBackground(Color.LIGHT_GRAY);
    }


}
